
export const months={
  "01":{key:'01',name:"មករា"},
  "02":{key:'02',name:"កុម្ភៈ"},
  "03":{key:'03',name:"មីនា"},
  "04":{key:'04',name:"មេសា"},
  "05":{key:'05',name:"ឧសភា"},
  "06":{key:'06',name:"មិថុនា"},
  "07":{key:'07',name:"កក្កដា"},
  "08":{key:'08',name:"សីហា"},
  "09":{key:'09',name:"កញ្ញា"},
  "10":{key:'10',name:"តុលា"},
  "11":{key:'11',name:"វិច្ឆិកា"},
  "12":{key:'12',name:"ធ្នូ"},
}
export const monthOfYear=[
  {key:'01',name:"មករា"},
  {key:'02',name:"កុម្ភៈ"},
  {key:'03',name:"មីនា"},
  {key:'04',name:"មេសា"},
  {key:'05',name:"ឧសភា"},
  {key:'06',name:"មិថុនា"},
  {key:'07',name:"កក្កដា"},
  {key:'08',name:"សីហា"},
  {key:'09',name:"កញ្ញា"},
  {key:'10',name:"តុលា"},
  {key:'11',name:"វិច្ឆិកា"},
  {key:'12',name:"ធ្នូ"},
]

export const days=[
  {key:"01",name:"1"},
  {key:"02",name:"2"},
  {key:"03",name:"3"},
  {key:"04",name:"4"},
  {key:"05",name:"5"},
  {key:"06",name:"6"},
  {key:"07",name:"7"},
  {key:"08",name:"8"},
  {key:"09",name:"9"},
  {key:"10",name:"10"},
  {key:"11",name:"11"},
  {key:"12",name:"12"},
  {key:"13",name:"13"},
  {key:"14",name:"14"},
  {key:"15",name:"15"},
  {key:"16",name:"16"},
  {key:"17",name:"17"},
  {key:"18",name:"18"},
  {key:"19",name:"19"},
  {key:"20",name:"20"},
  {key:"21",name:"21"},
  {key:"22",name:"22"},
  {key:"23",name:"23"},
  {key:"24",name:"24"},
  {key:"25",name:"25"},
  {key:"26",name:"26"},
  {key:"27",name:"27"},
  {key:"28",name:"28"},
  {key:"29",name:"29"},
  {key:"30",name:"30"},
  {key:"31",name:"31"},
]
export const province=[
  {key:"01",name:"Banteay Meanchey", native_name:"បន្ទាយមានជ័យ"},
  {key:"02",name:"Battambang", native_name:"បាត់ដំបង"},
  {key:"03",name:"Kampong Cham", native_name:"កំពង់ចាម"},
  {key:"04",name:"Kampong Chhnang", native_name:"កំពង់ឆ្នាំង"},
  {key:"05",name:"Kampong Speu", native_name:"កំពង់ស្ពឺ"},
  {key:"06",name:"Kampong Thom", native_name:"កំពង់ធំ"},
  {key:"07",name:"Kampot", native_name:"កំពត"},
  {key:"08",name:"Kandal", native_name:"កណ្តាល"},
  {key:"09",name:"Koh Kong", native_name:"កោះកុង"},
  {key:"10",name:"Kratié", native_name:"ក្រចេះ"},
  {key:"11",name:"Phnom Penh", native_name:"ភ្នំពេញ"},
  {key:"12",name:"Preah Vihear", native_name:"ព្រះវិហារ"},
  {key:"13",name:"Prey Veng", native_name:"ព្រៃវែង"},
  {key:"14",name:"Pursat", native_name:"ពោធិ៍សាត់"},
  {key:"15",name:"Ratanak Kiri", native_name:"រតនគិរី"},
  {key:"25",name:"Mondulkiri", native_name:"មណ្ឌលគិរី"},
  {key:"16",name:"Siem Reap", native_name:"សៀមរាប"},
  {key:"17",name:"Preah Sihanouk", native_name:"ព្រះសីហនុ"},
  {key:"18",name:"Steung Treng", native_name:"ស្ទឹងត្រែង"},
  {key:"19",name:"Svay Rieng", native_name:"ស្វាយរៀង"},
  {key:"20",name:"Takéo", native_name:"តាកែវ"},
  {key:"21",name:"Oddar Meanchey", native_name:"ឧត្តរមានជ័យ"},
  {key:"22",name:"Kep", native_name:"កែប"},
  {key:"23",name:"Pailin", native_name:"ប៉ៃលិន"},
  {key:"24",name:"Tboung Khmum", native_name:"ត្បូងឃ្មុំ"},
  

]